includes:
- ../projects/unit/configs/vqa2_dataset_cfg.yaml

other_configs:
  image_w: 224
  image_h: 224
  hidden_size: 768

dataset_config:
  vqa2:
    processors:
      image_processor:
        type: vilt_image_processor
        params:
          size:
          - ${other_configs.image_w}
          - ${other_configs.image_h}
      text_processor:
        type: vilt_text_tokenizer
        params:
          mask_probability: 0
          max_seq_length: 25

model_config:
  vilt:
    tasks: ${datasets}
    heads:
      vqa2:
        - type: mlp
          loss: vqa2_mlp
          freeze: false
          lr_multiplier: 1.0
          in_dim: 768
          hidden_size: 1536
          num_labels: 3129
          pooler_name: bert_pooler
    losses:
      vqa2: logit_bce

    image_encoder:
      type: vit
      params:
        random_init: True
        pretrained_model_name: google/vit-base-patch16-224
        gradient_checkpointing: false
        do_pooling: false
        hidden_dropout_prob: 0.1
        add_pooling_layer: False
        do_patch_embeddings: False
        image_size:
        - ${other_configs.image_w}
        - ${other_configs.image_h}
        regularize_bn: False
        regularize_bias: True
        hidden_dim: ${other_configs.hidden_size}
        pretrained_model: vit_base_patch16_224
        mlp_dim: 3072

    text_embeddings:
      type: vilt_text_embedding
      bert_model_name: bert-base-uncased
      hidden_dim: ${other_configs.hidden_size}
      hidden_size: 768


training:
  clip_gradients: false
  lr_scheduler: true
  max_updates: 44000
  checkpoint_interval: 4000
  evaluation_interval: 4000
  batch_size: 256 # 32 per GPU * 8 GPU
  find_unused_parameters: false


optimizer:
  type: adam_w_skip_params_with_zero_grad
  params:
    lr: 5e-5
    eps: 1e-8
    weight_decay: 1e-4


scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 4000
    num_training_steps: ${training.max_updates}


evaluation:
  metrics:
    - type: vqa_accuracy
      datasets:
      - vqa2
